package cn.gdcp.graduation.pojo;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "c_category")
public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_category.id
     *
     * @mbggenerated Wed Nov 06 22:26:18 CST 2019
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY,generator="Mysql")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_category.name
     *
     * @mbggenerated Wed Nov 06 22:26:18 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_category.id
     *
     * @return the value of c_category.id
     *
     * @mbggenerated Wed Nov 06 22:26:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_category.id
     *
     * @param id the value for c_category.id
     *
     * @mbggenerated Wed Nov 06 22:26:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_category.name
     *
     * @return the value of c_category.name
     *
     * @mbggenerated Wed Nov 06 22:26:18 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_category.name
     *
     * @param name the value for c_category.name
     *
     * @mbggenerated Wed Nov 06 22:26:18 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}
