package cn.gdcp.graduation.pojo;

import cn.gdcp.graduation.service.impl.OrderItemServiceImpl;
import cn.gdcp.graduation.service.impl.OrderServiceImpl;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "o_order")
public class Order {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.id
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY,generator="Mysql")
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.order_code
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    private String orderCode;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.address
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    private String address;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.post_code
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    private String postCode;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.receiver
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    private String receiver;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.mobile
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    private String mobile;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.user_message
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    private String userMessage;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.create_date
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    private Date createDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.pay_date
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    private Date payDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.delivery_date
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    private Date deliveryDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.confirm_date
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    private Date confirmDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.status
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.total_money
     * @mbggenerated  Mon Nov 11 00:02:11 CST 2019
     */
    private String totalMoney;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column o_order.total_number
     * @mbggenerated  Mon Nov 11 00:02:11 CST 2019
     */
    private String totalNumber;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.total_money
     * @return  the value of o_order.total_money
     * @mbggenerated  Mon Nov 11 00:02:11 CST 2019
     */
    public String getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.total_money
     * @param totalMoney  the value for o_order.total_money
     * @mbggenerated  Mon Nov 11 00:02:11 CST 2019
     */
    public void setTotalMoney(String totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.total_number
     * @return  the value of o_order.total_number
     * @mbggenerated  Mon Nov 11 00:02:11 CST 2019
     */
    public String getTotalNumber() {
        return totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.total_number
     * @param totalNumber  the value for o_order.total_number
     * @mbggenerated  Mon Nov 11 00:02:11 CST 2019
     */
    public void setTotalNumber(String totalNumber) {
        this.totalNumber = totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.id
     * @return  the value of o_order.id
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.id
     * @param id  the value for o_order.id
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.order_code
     * @return  the value of o_order.order_code
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.order_code
     * @param orderCode  the value for o_order.order_code
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.address
     * @return  the value of o_order.address
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.address
     * @param address  the value for o_order.address
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.post_code
     * @return  the value of o_order.post_code
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.post_code
     * @param postCode  the value for o_order.post_code
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.receiver
     * @return  the value of o_order.receiver
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.receiver
     * @param receiver  the value for o_order.receiver
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.mobile
     * @return  the value of o_order.mobile
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.mobile
     * @param mobile  the value for o_order.mobile
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.user_message
     * @return  the value of o_order.user_message
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public String getUserMessage() {
        return userMessage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.user_message
     * @param userMessage  the value for o_order.user_message
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public void setUserMessage(String userMessage) {
        this.userMessage = userMessage;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.create_date
     * @return  the value of o_order.create_date
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.create_date
     * @param createDate  the value for o_order.create_date
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.pay_date
     * @return  the value of o_order.pay_date
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.pay_date
     * @param payDate  the value for o_order.pay_date
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.delivery_date
     * @return  the value of o_order.delivery_date
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public Date getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.delivery_date
     * @param deliveryDate  the value for o_order.delivery_date
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.confirm_date
     * @return  the value of o_order.confirm_date
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public Date getConfirmDate() {
        return confirmDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.confirm_date
     * @param confirmDate  the value for o_order.confirm_date
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public void setConfirmDate(Date confirmDate) {
        this.confirmDate = confirmDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column o_order.status
     * @return  the value of o_order.status
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column o_order.status
     * @param status  the value for o_order.status
     * @mbggenerated  Thu Nov 07 23:48:22 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}