package cn.gdcp.graduation.pojo;

import javax.persistence.*;

@Table(name = "o_orderitem")
public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_orderitem.id
     *
     * @mbggenerated Fri Nov 08 22:41:37 CST 2019
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY,generator="Mysql")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_orderitem.number
     *
     * @mbggenerated Fri Nov 08 22:41:37 CST 2019
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_orderitem.id
     *
     * @return the value of o_orderitem.id
     *
     * @mbggenerated Fri Nov 08 22:41:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_orderitem.id
     *
     * @param id the value for o_orderitem.id
     *
     * @mbggenerated Fri Nov 08 22:41:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_orderitem.number
     *
     * @return the value of o_orderitem.number
     *
     * @mbggenerated Fri Nov 08 22:41:37 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_orderitem.number
     *
     * @param number the value for o_orderitem.number
     *
     * @mbggenerated Fri Nov 08 22:41:37 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    @Transient
    private Product product;

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }
}