package cn.gdcp.graduation.pojo;

import javax.persistence.Table;

@Table(name = "o_orderitem_product_key")
public class OrderItemProductKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_orderitem_product_key.oi_id
     *
     * @mbggenerated Sun Nov 24 17:26:56 CST 2019
     */
    private Integer oiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_orderitem_product_key.p_id
     *
     * @mbggenerated Sun Nov 24 17:26:56 CST 2019
     */
    private Integer pId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_orderitem_product_key.oi_id
     *
     * @return the value of o_orderitem_product_key.oi_id
     *
     * @mbggenerated Sun Nov 24 17:26:56 CST 2019
     */
    public Integer getOiId() {
        return oiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_orderitem_product_key.oi_id
     *
     * @param oiId the value for o_orderitem_product_key.oi_id
     *
     * @mbggenerated Sun Nov 24 17:26:56 CST 2019
     */
    public void setOiId(Integer oiId) {
        this.oiId = oiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_orderitem_product_key.p_id
     *
     * @return the value of o_orderitem_product_key.p_id
     *
     * @mbggenerated Sun Nov 24 17:26:56 CST 2019
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_orderitem_product_key.p_id
     *
     * @param pId the value for o_orderitem_product_key.p_id
     *
     * @mbggenerated Sun Nov 24 17:26:56 CST 2019
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }
}