package cn.gdcp.graduation.pojo;

import javax.persistence.Table;

@Table(name = "o_order_orderitem_key")
public class OrderOrderItemKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order_orderitem_key.o_id
     *
     * @mbggenerated Fri Nov 29 23:47:57 CST 2019
     */
    private Integer oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order_orderitem_key.oi_id
     *
     * @mbggenerated Fri Nov 29 23:47:57 CST 2019
     */
    private Integer oiId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order_orderitem_key.o_id
     *
     * @return the value of o_order_orderitem_key.o_id
     *
     * @mbggenerated Fri Nov 29 23:47:57 CST 2019
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order_orderitem_key.o_id
     *
     * @param oId the value for o_order_orderitem_key.o_id
     *
     * @mbggenerated Fri Nov 29 23:47:57 CST 2019
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order_orderitem_key.oi_id
     *
     * @return the value of o_order_orderitem_key.oi_id
     *
     * @mbggenerated Fri Nov 29 23:47:57 CST 2019
     */
    public Integer getOiId() {
        return oiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order_orderitem_key.oi_id
     *
     * @param oiId the value for o_order_orderitem_key.oi_id
     *
     * @mbggenerated Fri Nov 29 23:47:57 CST 2019
     */
    public void setOiId(Integer oiId) {
        this.oiId = oiId;
    }
}
