package cn.gdcp.graduation.pojo;

import javax.persistence.Table;

@Table(name = "c_product_productimage_key")
public class ProductProductImageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product_productimage_key.p_id
     *
     * @mbggenerated Tue Nov 12 13:13:37 CST 2019
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product_productimage_key.pi_id
     *
     * @mbggenerated Tue Nov 12 13:13:37 CST 2019
     */
    private Integer piId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product_productimage_key.p_id
     *
     * @return the value of c_product_productimage_key.p_id
     *
     * @mbggenerated Tue Nov 12 13:13:37 CST 2019
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product_productimage_key.p_id
     *
     * @param pId the value for c_product_productimage_key.p_id
     *
     * @mbggenerated Tue Nov 12 13:13:37 CST 2019
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product_productimage_key.pi_id
     *
     * @return the value of c_product_productimage_key.pi_id
     *
     * @mbggenerated Tue Nov 12 13:13:37 CST 2019
     */
    public Integer getPiId() {
        return piId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product_productimage_key.pi_id
     *
     * @param piId the value for c_product_productimage_key.pi_id
     *
     * @mbggenerated Tue Nov 12 13:13:37 CST 2019
     */
    public void setPiId(Integer piId) {
        this.piId = piId;
    }
}
