package cn.gdcp.graduation.pojo;

import javax.persistence.*;
import java.util.Date;

@Table(name = "c_product")
public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.id
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY,generator="Mysql")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.name
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.subTitle
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    private String subTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.originalPrice
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    private Float originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.promotePrice
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    private Float promotePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.stock
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.salesVolume
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    private Integer salesVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.createTime
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column c_product.cid
     * @mbggenerated  Thu Nov 07 11:16:29 CST 2019
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column c_product.cid
     * @return  the value of c_product.cid
     * @mbggenerated  Thu Nov 07 11:16:29 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column c_product.cid
     * @param cid  the value for c_product.cid
     * @mbggenerated  Thu Nov 07 11:16:29 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.id
     *
     * @return the value of c_product.id
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.id
     *
     * @param id the value for c_product.id
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.name
     *
     * @return the value of c_product.name
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.name
     *
     * @param name the value for c_product.name
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.subTitle
     *
     * @return the value of c_product.subTitle
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.subTitle
     *
     * @param subTitle the value for c_product.subTitle
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.originalPrice
     *
     * @return the value of c_product.originalPrice
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public Float getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.originalPrice
     *
     * @param originalPrice the value for c_product.originalPrice
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public void setOriginalPrice(Float originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.promotePrice
     *
     * @return the value of c_product.promotePrice
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public Float getPromotePrice() {
        return promotePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.promotePrice
     *
     * @param promotePrice the value for c_product.promotePrice
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public void setPromotePrice(Float promotePrice) {
        this.promotePrice = promotePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.stock
     *
     * @return the value of c_product.stock
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.stock
     *
     * @param stock the value for c_product.stock
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.salesVolume
     *
     * @return the value of c_product.salesVolume
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public Integer getSalesVolume() {
        return salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.salesVolume
     *
     * @param salesVolume the value for c_product.salesVolume
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public void setSalesVolume(Integer salesVolume) {
        this.salesVolume = salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.createTime
     *
     * @return the value of c_product.createTime
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.createTime
     *
     * @param createTime the value for c_product.createTime
     *
     * @mbggenerated Thu Nov 07 10:20:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Transient
    private Integer firstProductImage;

    public Integer getFirstProductImage() {
        return firstProductImage;
    }

    public void setFirstProductImage(Integer firstProductImage) {
        this.firstProductImage = firstProductImage;
    }
}