package cn.gdcp.graduation.pojo;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "c_propertyvalue")
public class PropertyValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_propertyvalue.id
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY,generator="Mysql")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_propertyvalue.license_on
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    private String licenseOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_propertyvalue.expiration_date
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    private String expirationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_propertyvalue.producing_area
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    private String producingArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_propertyvalue.province
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_propertyvalue.city
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_propertyvalue.grade
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_propertyvalue.standard
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    private String standard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_propertyvalue.storage_method
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    private String storageMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_propertyvalue.growing_season
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    private String growingSeason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_propertyvalue.net_content
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    private String netContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_propertyvalue.pid
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_propertyvalue.id
     *
     * @return the value of c_propertyvalue.id
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_propertyvalue.id
     *
     * @param id the value for c_propertyvalue.id
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_propertyvalue.license_on
     *
     * @return the value of c_propertyvalue.license_on
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public String getLicenseOn() {
        return licenseOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_propertyvalue.license_on
     *
     * @param licenseOn the value for c_propertyvalue.license_on
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public void setLicenseOn(String licenseOn) {
        this.licenseOn = licenseOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_propertyvalue.expiration_date
     *
     * @return the value of c_propertyvalue.expiration_date
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public String getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_propertyvalue.expiration_date
     *
     * @param expirationDate the value for c_propertyvalue.expiration_date
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public void setExpirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_propertyvalue.producing_area
     *
     * @return the value of c_propertyvalue.producing_area
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public String getProducingArea() {
        return producingArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_propertyvalue.producing_area
     *
     * @param producingArea the value for c_propertyvalue.producing_area
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public void setProducingArea(String producingArea) {
        this.producingArea = producingArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_propertyvalue.province
     *
     * @return the value of c_propertyvalue.province
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_propertyvalue.province
     *
     * @param province the value for c_propertyvalue.province
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_propertyvalue.city
     *
     * @return the value of c_propertyvalue.city
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_propertyvalue.city
     *
     * @param city the value for c_propertyvalue.city
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_propertyvalue.grade
     *
     * @return the value of c_propertyvalue.grade
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_propertyvalue.grade
     *
     * @param grade the value for c_propertyvalue.grade
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_propertyvalue.standard
     *
     * @return the value of c_propertyvalue.standard
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_propertyvalue.standard
     *
     * @param standard the value for c_propertyvalue.standard
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public void setStandard(String standard) {
        this.standard = standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_propertyvalue.storage_method
     *
     * @return the value of c_propertyvalue.storage_method
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public String getStorageMethod() {
        return storageMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_propertyvalue.storage_method
     *
     * @param storageMethod the value for c_propertyvalue.storage_method
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public void setStorageMethod(String storageMethod) {
        this.storageMethod = storageMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_propertyvalue.growing_season
     *
     * @return the value of c_propertyvalue.growing_season
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public String getGrowingSeason() {
        return growingSeason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_propertyvalue.growing_season
     *
     * @param growingSeason the value for c_propertyvalue.growing_season
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public void setGrowingSeason(String growingSeason) {
        this.growingSeason = growingSeason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_propertyvalue.net_content
     *
     * @return the value of c_propertyvalue.net_content
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public String getNetContent() {
        return netContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_propertyvalue.net_content
     *
     * @param netContent the value for c_propertyvalue.net_content
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public void setNetContent(String netContent) {
        this.netContent = netContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_propertyvalue.pid
     *
     * @return the value of c_propertyvalue.pid
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_propertyvalue.pid
     *
     * @param pid the value for c_propertyvalue.pid
     *
     * @mbggenerated Thu Nov 07 21:25:52 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}
