package cn.gdcp.graduation.pojo;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "u_review")
public class Review {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_review.id
     *
     * @mbggenerated Sun Dec 01 17:38:37 CST 2019
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY,generator="Mysql")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_review.content
     *
     * @mbggenerated Sun Dec 01 17:38:37 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_review.createTime
     *
     * @mbggenerated Sun Dec 01 17:38:37 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_review.id
     *
     * @return the value of u_review.id
     *
     * @mbggenerated Sun Dec 01 17:38:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_review.id
     *
     * @param id the value for u_review.id
     *
     * @mbggenerated Sun Dec 01 17:38:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_review.content
     *
     * @return the value of u_review.content
     *
     * @mbggenerated Sun Dec 01 17:38:37 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_review.content
     *
     * @param content the value for u_review.content
     *
     * @mbggenerated Sun Dec 01 17:38:37 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_review.createTime
     *
     * @return the value of u_review.createTime
     *
     * @mbggenerated Sun Dec 01 17:38:37 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_review.createTime
     *
     * @param createTime the value for u_review.createTime
     *
     * @mbggenerated Sun Dec 01 17:38:37 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
