package cn.gdcp.graduation.pojo;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "u_user")
public class User {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.id
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY,generator="Mysql")
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.username
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.password
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.phone
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    private String phone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.email
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.id
     * @return  the value of u_user.id
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.id
     * @param id  the value for u_user.id
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.username
     * @return  the value of u_user.username
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.username
     * @param name  the value for u_user.username
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.password
     * @return  the value of u_user.password
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.password
     * @param password  the value for u_user.password
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.phone
     * @return  the value of u_user.phone
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.phone
     * @param phone  the value for u_user.phone
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.email
     * @return  the value of u_user.email
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.email
     * @param email  the value for u_user.email
     * @mbggenerated  Thu Nov 07 22:53:06 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }
}
