package cn.gdcp.graduation.pojo;

import javax.persistence.Table;

@Table(name = "u_user_orderitem_key")
public class UserOrderItemKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_orderitem_key.u_id
     *
     * @mbggenerated Sat Nov 30 00:09:06 CST 2019
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_orderitem_key.oi_id
     *
     * @mbggenerated Sat Nov 30 00:09:06 CST 2019
     */
    private Integer oiId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_orderitem_key.u_id
     *
     * @return the value of u_user_orderitem_key.u_id
     *
     * @mbggenerated Sat Nov 30 00:09:06 CST 2019
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_orderitem_key.u_id
     *
     * @param uId the value for u_user_orderitem_key.u_id
     *
     * @mbggenerated Sat Nov 30 00:09:06 CST 2019
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_orderitem_key.oi_id
     *
     * @return the value of u_user_orderitem_key.oi_id
     *
     * @mbggenerated Sat Nov 30 00:09:06 CST 2019
     */
    public Integer getOiId() {
        return oiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_orderitem_key.oi_id
     *
     * @param oiId the value for u_user_orderitem_key.oi_id
     *
     * @mbggenerated Sat Nov 30 00:09:06 CST 2019
     */
    public void setOiId(Integer oiId) {
        this.oiId = oiId;
    }
}
