package cn.gdcp.graduation.pojo;

import javax.persistence.Table;

@Table(name = "u_user_review_key")
public class UserReviewKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_review_key.u_id
     *
     * @mbggenerated Sun Dec 01 19:26:20 CST 2019
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_review_key.ur_id
     *
     * @mbggenerated Sun Dec 01 19:26:20 CST 2019
     */
    private Integer urId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_review_key.u_id
     *
     * @return the value of u_user_review_key.u_id
     *
     * @mbggenerated Sun Dec 01 19:26:20 CST 2019
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_review_key.u_id
     *
     * @param uId the value for u_user_review_key.u_id
     *
     * @mbggenerated Sun Dec 01 19:26:20 CST 2019
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_review_key.ur_id
     *
     * @return the value of u_user_review_key.ur_id
     *
     * @mbggenerated Sun Dec 01 19:26:20 CST 2019
     */
    public Integer getUrId() {
        return urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_review_key.ur_id
     *
     * @param urId the value for u_user_review_key.ur_id
     *
     * @mbggenerated Sun Dec 01 19:26:20 CST 2019
     */
    public void setUrId(Integer urId) {
        this.urId = urId;
    }
}