package cn.gdcp.graduation.pojo;

import javax.persistence.Table;

@Table(name = "u_user_order_key")
public class UserOrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_user_order_key.u_id
     *
     * @mbggenerated Mon Nov 11 13:06:05 CST 2019
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_user_order_key.o_id
     *
     * @mbggenerated Mon Nov 11 13:06:05 CST 2019
     */
    private Integer oId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_user_order_key.u_id
     *
     * @return the value of o_user_order_key.u_id
     *
     * @mbggenerated Mon Nov 11 13:06:05 CST 2019
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_user_order_key.u_id
     *
     * @param uId the value for o_user_order_key.u_id
     *
     * @mbggenerated Mon Nov 11 13:06:05 CST 2019
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_user_order_key.o_id
     *
     * @return the value of o_user_order_key.o_id
     *
     * @mbggenerated Mon Nov 11 13:06:05 CST 2019
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_user_order_key.o_id
     *
     * @param oId the value for o_user_order_key.o_id
     *
     * @mbggenerated Mon Nov 11 13:06:05 CST 2019
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }
}